"""
report/content_builder.py
=========================
Assembles report sections from the snapshot context.

The renderer iterates ``SECTION_ORDER`` from ``template.py`` and calls
the matching ``build_<name>(ctx)`` function here. Each builder returns
a list of ReportLab flowables that will be appended to the document
Story.

Rules every builder follows
---------------------------
1. **Source-driven.** Builders consume what's in the context dict. They
   do not call out to the data layer or recompute anything.
2. **Missing-data behavior.** If the input for a section is absent, the
   builder returns a section header plus a labeled placeholder. The
   section never silently disappears.
3. **Deterministic.** Builders sort/order content from input data only.
   No random sampling, no wall-clock-dependent branching.
4. **Bounded prose.** Long inputs (thesis essay, filings list) are
   rendered as separate paragraphs so the renderer can page-break
   cleanly between them.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any, Optional

from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import (
    Flowable,
    KeepTogether,
    PageBreak,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from .charts import ChartSpec, build_chart_flowables
from .template import DEFAULT_THEME, REPORT_VERSION, RENDERER_VERSION, DocTheme

logger = logging.getLogger(__name__)


# =============================================================================
# Public dispatch
# =============================================================================


def build_section(
    name: str, ctx: dict, theme: DocTheme = DEFAULT_THEME,
) -> list[Flowable]:
    """Dispatch a section name to its builder.

    Unknown section names produce a placeholder rather than crashing —
    that way a mis-edited ``SECTION_ORDER`` doesn't kill the run.
    """
    builder = {
        "title_page":         build_title_page,
        "executive_summary":  build_executive_summary,
        "thesis":             build_thesis,
        "key_metrics":        build_key_metrics,
        "charts":             build_charts,
        "risk_commentary":    build_risk_commentary,
        "supporting_context": build_supporting_context,
        "appendix":           build_appendix,
    }.get(name)

    if builder is None:
        styles = theme.styles()
        return [
            Paragraph(f"<b>Unknown section: {_escape(name)}</b>", styles["H2"]),
            Paragraph(
                "This section name is listed in SECTION_ORDER but has no "
                "matching builder in content_builder.py.",
                styles["Placeholder"],
            ),
        ]

    try:
        return builder(ctx, theme)
    except Exception as e:  # noqa: BLE001 — section failure must not kill the report
        logger.exception("content_builder | section %s raised", name)
        styles = theme.styles()
        return [
            Paragraph(_section_title(name), styles["H1"]),
            Paragraph(
                f"Section '{name}' failed to render: {_escape(str(e))}",
                styles["Placeholder"],
            ),
        ]


# =============================================================================
# Title page
# =============================================================================


def build_title_page(ctx: dict, theme: DocTheme) -> list[Flowable]:
    styles = theme.styles()
    out: list[Flowable] = []

    # Top spacing pushes the title visually into the upper third
    out.append(Spacer(1, 1.2 * inch))

    title = ctx.get("report_title") or "Investment Memorandum"
    out.append(Paragraph(_escape(title), styles["Title"]))

    # Subtitle: ticker or portfolio scope, whichever applies
    subtitle = _scope_label(ctx)
    out.append(Paragraph(_escape(subtitle), styles["Subtitle"]))

    # Snapshot date + generated-at line
    snap_date = ctx.get("snapshot_date") or ctx.get("as_of") or "n/a"
    generated_at = ctx.get("generated_at") or _now_iso()
    snapshot_id = ctx.get("snapshot_id") or "(none)"
    analyst = ctx.get("analyst") or "Ary Fund Research System"

    meta_rows = [
        ("Snapshot as of", str(snap_date)),
        ("Generated at",   str(generated_at)),
        ("Snapshot ID",    str(snapshot_id)),
        ("Prepared by",    str(analyst)),
        ("Report version", REPORT_VERSION),
        ("Renderer",       RENDERER_VERSION),
    ]
    out.append(Spacer(1, 0.6 * inch))
    out.append(_meta_table(meta_rows, theme))

    # Disclaimer at the bottom
    out.append(Spacer(1, 1.4 * inch))
    disclaimer = (
        "<i>This memorandum is generated by an automated research system "
        "and is intended for internal review. Inputs are taken from public "
        "filings, market data, and macro indicators as of the snapshot "
        "date. Past performance is not indicative of future results. "
        "Nothing herein constitutes investment advice.</i>"
    )
    out.append(Paragraph(disclaimer, styles["Meta"]))
    out.append(PageBreak())
    return out


# =============================================================================
# Executive summary
# =============================================================================


def build_executive_summary(ctx: dict, theme: DocTheme) -> list[Flowable]:
    styles = theme.styles()
    thesis = ctx.get("thesis") or {}
    risk = ctx.get("risk") or ctx.get("risk_flags") or {}

    out: list[Flowable] = [Paragraph("Executive Summary", styles["H1"])]

    if not thesis and not risk:
        out.append(_placeholder(
            "No thesis or risk summary present in this snapshot. "
            "Verify that the agent chain completed before requesting a report.",
            theme,
        ))
        return out

    # Outlook badge row — outlook, direction, confidence, combined risk
    outlook = thesis.get("outlook") or "neutral"
    direction = thesis.get("price_direction") or "flat"
    conf = _as_float(thesis.get("confidence"))
    conf_pct = f"{conf:.0%}" if conf is not None else "n/a"
    combined_risk = (risk.get("levels") or {}).get("combined") or "n/a"

    badges = [
        ("Outlook",       outlook.upper()),
        ("Direction",     direction.replace("_", " ").upper()),
        ("Confidence",    conf_pct),
        ("Combined Risk", str(combined_risk).upper()),
    ]
    out.append(_badge_row(badges, theme))
    out.append(Spacer(1, 8))

    # Headline summary sentence
    summary = (
        thesis.get("summary")
        or thesis.get("rationale")
        or "(No summary provided.)"
    )
    out.append(Paragraph(
        f"<b>Summary.</b> {_escape(summary)}",
        styles["Body"],
    ))

    # Top risks + opportunities — capped lists keep the page calm
    risks = (thesis.get("key_risks") or [])[:5]
    opps = (thesis.get("key_opportunities") or [])[:5]
    if risks:
        out.append(Paragraph("<b>Key risks</b>", styles["H3"]))
        out.append(_bulleted(risks, theme))
    if opps:
        out.append(Paragraph("<b>Key opportunities</b>", styles["H3"]))
        out.append(_bulleted(opps, theme))

    return out


# =============================================================================
# Thesis
# =============================================================================


def build_thesis(ctx: dict, theme: DocTheme) -> list[Flowable]:
    styles = theme.styles()
    essay = ctx.get("essay") or {}
    thesis = ctx.get("thesis") or {}

    out: list[Flowable] = [Paragraph("Investment Thesis", styles["H1"])]

    text = (essay.get("text") if isinstance(essay, dict) else None) or ""
    text = text.strip()
    if not text:
        # No essay → fall back to the structured thesis fields, if present
        rationale = thesis.get("rationale")
        if rationale:
            out.append(Paragraph(_escape(rationale), styles["Body"]))
        else:
            out.append(_placeholder(
                "Thesis essay unavailable in snapshot.",
                theme,
            ))
        return out

    # Render the essay as one Paragraph per non-empty line/block. This
    # gives the renderer page-break points between paragraphs, which is
    # crucial for long essays.
    blocks = _split_essay_blocks(text)
    for block in blocks:
        # Headings in markdown-ish form: ## Foo / **Foo.**
        style_name, body = _classify_block(block)
        out.append(Paragraph(_escape_with_markup(body), styles[style_name]))

    # If the essay was a deterministic fallback, note that openly
    if isinstance(essay, dict) and essay.get("fallback"):
        out.append(Paragraph(
            "<i>Note: this thesis essay was produced by the deterministic "
            "fallback writer because the LLM was unavailable. Numeric "
            "claims are taken verbatim from the structured inputs.</i>",
            styles["Meta"],
        ))

    return out


# =============================================================================
# Key metrics
# =============================================================================


def build_key_metrics(ctx: dict, theme: DocTheme) -> list[Flowable]:
    styles = theme.styles()
    out: list[Flowable] = [Paragraph("Key Metrics", styles["H1"])]

    metrics = ctx.get("metrics") or ctx.get("key_metrics") or {}
    prices = ctx.get("prices") or {}
    if not metrics and not prices:
        out.append(_placeholder(
            "No metric snapshot present in this snapshot.",
            theme,
        ))
        return out

    # Curated, ordered view of the metrics every memo cares about.
    # Sources tried in priority order; first hit wins.
    groups = [
        ("Valuation", [
            ("P/E (trailing)",    _first(metrics, ("pe_ratio", "trailing_pe", "p_e"))),
            ("P/E (forward)",     _first(metrics, ("forward_pe", "forward_p_e"))),
            ("EV / EBITDA",       _first(metrics, ("ev_ebitda", "ev_to_ebitda"))),
            ("P / Sales",         _first(metrics, ("ps_ratio", "price_to_sales"))),
            ("Market cap",        _money(_first(prices, ("market_cap",))
                                         or _first(metrics, ("market_cap",)))),
        ]),
        ("Growth & Margins", [
            ("Revenue growth (YoY)", _pct(_first(metrics, ("revenue_growth", "revenue_growth_yoy")))),
            ("Gross margin",         _pct(_first(metrics, ("gross_margin",)))),
            ("Operating margin",     _pct(_first(metrics, ("operating_margin",)))),
            ("Net margin",           _pct(_first(metrics, ("net_margin",)))),
            ("FCF yield",            _pct(_first(metrics, ("fcf_yield", "free_cash_flow_yield")))),
        ]),
        ("Balance Sheet & Risk", [
            ("Debt / EBITDA",   _first(metrics, ("debt_ebitda", "debt_to_ebitda"))),
            ("Net debt / EBITDA", _first(metrics, ("net_debt_ebitda", "net_debt_to_ebitda"))),
            ("Interest coverage", _first(metrics, ("interest_coverage",))),
            ("Beta",              _first(metrics, ("beta",))),
            ("52w drawdown",      _pct(_first(metrics, ("drawdown", "max_drawdown")))),
        ]),
    ]

    rendered_groups = 0
    for group_name, rows in groups:
        # Filter rows that have at least one non-None value, so empty
        # sections (e.g. for a brand-new ticker with no fundamentals)
        # don't render as a wall of n/a.
        rows_clean = [
            (name, _fmt_metric(val)) for name, val in rows
            if val is not None
        ]
        if not rows_clean:
            continue
        rendered_groups += 1
        out.append(Paragraph(group_name, styles["H3"]))
        out.append(_two_col_table(rows_clean, theme))
        out.append(Spacer(1, 4))

    if rendered_groups == 0:
        # Belt-and-braces: a context with `metrics`/`prices` present but
        # none of the canonical fields populated still gets a clear note
        # rather than an empty section.
        out.append(_placeholder(
            "Metric snapshot present but no standard fields populated.",
            theme,
        ))

    return out


# =============================================================================
# Charts
# =============================================================================


def build_charts(ctx: dict, theme: DocTheme) -> list[Flowable]:
    styles = theme.styles()
    out: list[Flowable] = [Paragraph("Charts", styles["H1"])]

    charts_raw = ctx.get("charts")
    specs = _coerce_chart_list(charts_raw)
    if not specs:
        out.append(_placeholder(
            "No chart artifacts available for this snapshot.",
            theme,
        ))
        return out

    out.extend(build_chart_flowables(specs, theme))
    return out


# =============================================================================
# Risk commentary
# =============================================================================


def build_risk_commentary(ctx: dict, theme: DocTheme) -> list[Flowable]:
    styles = theme.styles()
    out: list[Flowable] = [Paragraph("Risk Commentary", styles["H1"])]

    risk = ctx.get("risk") or ctx.get("risk_flags") or {}
    if not risk:
        out.append(_placeholder(
            "No risk summary present in this snapshot.",
            theme,
        ))
        return out

    levels = risk.get("levels") or {}
    reasons = risk.get("reasons") or {}

    # Headline combined level
    combined = (levels.get("combined") or "n/a").upper()
    out.append(Paragraph(
        f"<b>Combined risk level:</b> {_escape(combined)}",
        styles["Body"],
    ))

    # Per-component breakdown — stable order
    for component in ("fundamental", "macro", "market", "agent"):
        lvl = levels.get(component)
        if lvl is None:
            continue
        out.append(Paragraph(
            f"{component.title()}: {_escape(str(lvl).upper())}",
            styles["H3"],
        ))
        comp_reasons = reasons.get(component) if isinstance(reasons, dict) else None
        if comp_reasons:
            real = [r for r in comp_reasons if r and r != "no data"]
            if real:
                out.append(_bulleted(real[:6], theme))
                continue
        out.append(Paragraph(
            "<i>No specific reasons recorded.</i>",
            styles["BodyMuted"],
        ))

    # If reasons came as a flat list (simpler caller), surface that too
    if isinstance(reasons, list) and reasons:
        real = [r for r in reasons if r and r != "no data"]
        if real:
            out.append(Paragraph("Additional risk notes", styles["H3"]))
            out.append(_bulleted(real[:8], theme))

    return out


# =============================================================================
# Supporting context
# =============================================================================


def build_supporting_context(ctx: dict, theme: DocTheme) -> list[Flowable]:
    styles = theme.styles()
    out: list[Flowable] = [Paragraph("Supporting Context", styles["H1"])]

    rendered_any = False

    # ---- Filings summary ---------------------------------------------------
    filings_section = _build_filings_section(ctx, theme)
    if filings_section:
        out.extend(filings_section)
        rendered_any = True

    # ---- Macro summary -----------------------------------------------------
    macro_section = _build_macro_section(ctx, theme)
    if macro_section:
        out.extend(macro_section)
        rendered_any = True

    # ---- Derived signals ---------------------------------------------------
    derived_section = _build_derived_section(ctx, theme)
    if derived_section:
        out.extend(derived_section)
        rendered_any = True

    # ---- Sentiment / geo (only if present) --------------------------------
    extra_section = _build_extra_context_section(ctx, theme)
    if extra_section:
        out.extend(extra_section)
        rendered_any = True

    if not rendered_any:
        out.append(_placeholder(
            "No supporting context (filings / macro / derived signals) "
            "present in this snapshot.",
            theme,
        ))

    return out


def _build_filings_section(ctx: dict, theme: DocTheme) -> list[Flowable]:
    styles = theme.styles()
    filings = ctx.get("filings") or ctx.get("filings_summary")
    if not filings:
        return []
    out = [Paragraph("Recent Filings", styles["H2"])]

    # Two shapes: a list of dicts (pipeline.build_agent_context) OR a
    # year-keyed dict (filing_analyzer.summarize_filings_by_year).
    rows: list[tuple[str, str, str]] = []  # (date, type, snippet)

    if isinstance(filings, list):
        for f in filings[:8]:
            if not isinstance(f, dict):
                continue
            rows.append((
                str(f.get("filed_date") or f.get("date") or ""),
                str(f.get("filing_type") or f.get("form") or ""),
                _truncate(str(f.get("description") or f.get("summary") or ""), 160),
            ))
    elif isinstance(filings, dict):
        # Either {year: {form: text}} OR {"recent": [...], "red_flags": [...]}
        if "recent" in filings or "red_flags" in filings:
            recent = filings.get("recent") or []
            for f in recent[:8]:
                if isinstance(f, dict):
                    rows.append((
                        str(f.get("filed_date") or ""),
                        str(f.get("filing_type") or ""),
                        _truncate(str(f.get("description") or ""), 160),
                    ))
        else:
            for year in sorted(filings.keys(), reverse=True):
                forms = filings[year]
                if not isinstance(forms, dict):
                    continue
                for form, text in forms.items():
                    rows.append((str(year), str(form), _truncate(str(text), 160)))

    if not rows:
        out.append(Paragraph(
            "<i>Filings present in snapshot but no parseable rows.</i>",
            styles["BodyMuted"],
        ))
        return out

    # Stable sort by date descending so re-runs produce identical layout
    rows.sort(key=lambda r: r[0], reverse=True)
    table_data = [["Date", "Form", "Note"]] + rows[:8]
    out.append(_table(table_data, theme, col_widths=[1.0 * inch, 0.8 * inch, 4.6 * inch]))
    return out


def _build_macro_section(ctx: dict, theme: DocTheme) -> list[Flowable]:
    styles = theme.styles()
    macro = ctx.get("macro") or {}
    if not macro:
        return []
    out = [Paragraph("Macro Snapshot", styles["H2"])]

    interesting = [
        ("VIX",                   _first(macro, ("vix", "global.vix"))),
        ("2s10s spread",          _first(macro, ("yield_curve_spread", "yield_curve_2y10y", "global.yield_curve_2y10y"))),
        ("Yield curve inverted",  _first(macro, ("yield_curve_inverted",))),
        ("Recession probability", _pct(_first(macro, ("recession_probability", "global.recession_prob")))),
        ("HY OAS",                _first(macro, ("hy_oas", "global.hy_oas"))),
        ("Financial stress",      _first(macro, ("financial_stress", "global.financial_stress"))),
        ("CPI YoY",               _pct(_first(macro, ("cpi_yoy_pct", "cpi_yoy")))),
        ("Unemployment rate",     _pct(_first(macro, ("unemployment_rate",)))),
    ]
    rows = [(name, _fmt_metric(val)) for name, val in interesting if val is not None]
    if not rows:
        out.append(Paragraph(
            "<i>Macro dict present but no recognizable fields populated.</i>",
            styles["BodyMuted"],
        ))
        return out
    out.append(_two_col_table(rows, theme))
    return out


def _build_derived_section(ctx: dict, theme: DocTheme) -> list[Flowable]:
    styles = theme.styles()
    derived = ctx.get("derived") or ctx.get("signals") or {}
    if not derived:
        return []
    out = [Paragraph("Derived Signals", styles["H2"])]
    rows = [(k, _fmt_metric(v)) for k, v in sorted(derived.items()) if v is not None]
    if not rows:
        out.append(Paragraph(
            "<i>Derived signals present but empty.</i>",
            styles["BodyMuted"],
        ))
        return out
    out.append(_two_col_table(rows[:16], theme))
    return out


def _build_extra_context_section(ctx: dict, theme: DocTheme) -> list[Flowable]:
    """Sentiment + geopolitical, only if present in the snapshot."""
    styles = theme.styles()
    out: list[Flowable] = []
    for key, label in (("sentiment", "Sentiment"), ("geo", "Geopolitical Context")):
        section = ctx.get(key)
        if not section:
            continue
        out.append(Paragraph(label, styles["H2"]))
        if isinstance(section, str):
            out.append(Paragraph(_escape(section), styles["Body"]))
        elif isinstance(section, dict):
            rows = [(k, _fmt_metric(v)) for k, v in sorted(section.items())
                    if v is not None]
            if rows:
                out.append(_two_col_table(rows, theme))
        elif isinstance(section, list):
            out.append(_bulleted([str(x) for x in section[:8]], theme))
    return out


# =============================================================================
# Appendix
# =============================================================================


def build_appendix(ctx: dict, theme: DocTheme) -> list[Flowable]:
    styles = theme.styles()
    out: list[Flowable] = [Paragraph("Appendix & Sources", styles["H1"])]

    # 1) Data sources / provenance
    out.append(Paragraph("Data sources", styles["H2"]))
    sources = ctx.get("sources") or ctx.get("provenance") or {}
    if isinstance(sources, dict) and sources:
        rows = []
        for k, v in sorted(sources.items()):
            rows.append((k, _truncate(str(v), 80)))
        out.append(_two_col_table(rows, theme))
    elif isinstance(sources, list) and sources:
        out.append(_bulleted([str(s) for s in sources], theme))
    else:
        out.append(_placeholder(
            "No source / provenance metadata recorded in this snapshot.",
            theme,
        ))

    # 2) Missing-data summary — what we couldn't render
    out.append(Paragraph("Coverage notes", styles["H2"]))
    notes = _coverage_notes(ctx)
    if notes:
        out.append(_bulleted(notes, theme))
    else:
        out.append(Paragraph(
            "All expected sections were present in this snapshot.",
            styles["Body"],
        ))

    # 3) Methodology pointer
    out.append(Paragraph("Methodology", styles["H2"]))
    out.append(Paragraph(
        "This memo combines: rule-based fundamental and macro risk scoring, "
        "a heuristic 1-year thesis generator, an LLM-authored narrative "
        "essay (or deterministic fallback when offline), and a curated "
        "set of chart artifacts. See the project README for details on "
        "each component and on how to tune thresholds in "
        "<font face='Courier'>config.RISK_THRESHOLDS</font> and "
        "<font face='Courier'>thesis_generator</font> weights.",
        styles["Body"],
    ))

    # 4) Renderer / report metadata footer
    out.append(Paragraph("Report metadata", styles["H2"]))
    meta_rows = [
        ("Snapshot ID",      str(ctx.get("snapshot_id") or "(none)")),
        ("Snapshot date",    str(ctx.get("snapshot_date") or ctx.get("as_of") or "n/a")),
        ("Generated at",     str(ctx.get("generated_at") or _now_iso())),
        ("Report version",   REPORT_VERSION),
        ("Renderer version", RENDERER_VERSION),
        ("Output filename",  str(ctx.get("output_filename") or "(set by caller)")),
    ]
    out.append(_meta_table(meta_rows, theme))
    return out


def _coverage_notes(ctx: dict) -> list[str]:
    """Build a list of human-readable notes about what was missing."""
    notes: list[str] = []
    checks = [
        ("thesis essay",   bool((ctx.get("essay") or {}).get("text") if isinstance(ctx.get("essay"), dict) else False)),
        ("thesis summary", bool((ctx.get("thesis") or {}).get("summary"))),
        ("risk summary",   bool(ctx.get("risk") or ctx.get("risk_flags"))),
        ("metrics",        bool(ctx.get("metrics") or ctx.get("key_metrics"))),
        ("filings",        bool(ctx.get("filings") or ctx.get("filings_summary"))),
        ("macro",          bool(ctx.get("macro"))),
        ("charts",         bool(ctx.get("charts"))),
    ]
    for label, present in checks:
        if not present:
            notes.append(f"Section '{label}' was missing from the snapshot.")
    # Note explicit fallbacks the user should know about
    essay = ctx.get("essay")
    if isinstance(essay, dict) and essay.get("fallback"):
        notes.append("Thesis essay was generated by the deterministic fallback writer (LLM unavailable).")
    return notes


# =============================================================================
# Flowable helpers
# =============================================================================


def _table(
    data: list[list[Any]],
    theme: DocTheme,
    col_widths: Optional[list[float]] = None,
    header_row: bool = True,
) -> Flowable:
    """Standard report table: thin grid, alt row shading."""
    # Convert any cell-content non-strings via str(); allow Paragraph
    # objects to flow through untouched.
    rows = []
    for row in data:
        rows.append([
            cell if hasattr(cell, "wrap") else _cell_paragraph(cell, theme)
            for cell in row
        ])
    t = Table(rows, colWidths=col_widths, hAlign="LEFT", repeatRows=1 if header_row else 0)
    style = [
        ("VALIGN",     (0, 0), (-1, -1), "TOP"),
        ("FONTSIZE",   (0, 0), (-1, -1), theme.size_small),
        ("LEFTPADDING",  (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING",   (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 3),
        ("LINEBELOW",  (0, 0), (-1, 0), 0.5, theme.color_rule),
        ("LINEABOVE",  (0, 0), (-1, 0), 0.5, theme.color_rule),
        ("ROWBACKGROUNDS", (0, 1 if header_row else 0), (-1, -1),
            [colors.white, theme.color_table_bg_alt]),
    ]
    if header_row:
        style += [
            ("FONTNAME", (0, 0), (-1, 0), theme.font_body_bold),
            ("TEXTCOLOR", (0, 0), (-1, 0), theme.color_secondary),
        ]
    t.setStyle(TableStyle(style))
    return t


def _two_col_table(rows: list[tuple[str, Any]], theme: DocTheme) -> Flowable:
    """Tight two-column label/value table used for metrics."""
    return _table(
        [[label, value] for label, value in rows],
        theme,
        col_widths=[2.0 * inch, 4.0 * inch],
        header_row=False,
    )


def _meta_table(rows: list[tuple[str, str]], theme: DocTheme) -> Flowable:
    """Two-column metadata table, monospaced values for IDs / timestamps."""
    styles = theme.styles()
    body = [
        [Paragraph(f"<b>{_escape(k)}</b>", styles["Meta"]),
         Paragraph(_escape(v), styles["Mono"])]
        for k, v in rows
    ]
    t = Table(body, colWidths=[1.6 * inch, 4.4 * inch], hAlign="LEFT")
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING",  (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING",   (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 2),
    ]))
    return t


def _badge_row(items: list[tuple[str, str]], theme: DocTheme) -> Flowable:
    """Horizontal row of label/value badges used in the executive summary."""
    styles = theme.styles()
    cells = []
    for label, value in items:
        cells.append(
            Paragraph(
                f"<font size='{theme.size_small}' color='{theme.color_muted.hexval()}'>"
                f"{_escape(label.upper())}</font><br/>"
                f"<font size='{theme.size_h2}' color='{theme.color_primary.hexval()}'><b>"
                f"{_escape(value)}</b></font>",
                styles["Body"],
            )
        )
    t = Table([cells], hAlign="LEFT")
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 18),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    return t


def _bulleted(items: list[str], theme: DocTheme) -> Flowable:
    """Bullet list rendered as one Paragraph per bullet so it can paginate."""
    styles = theme.styles()
    body = "<br/>".join(
        f"• {_escape(str(item))}" for item in items
    )
    return Paragraph(body, styles["Body"])


def _cell_paragraph(value: Any, theme: DocTheme) -> Flowable:
    """Render a table cell value as a Paragraph so long strings wrap."""
    styles = theme.styles()
    if value is None:
        return Paragraph("<i>—</i>", styles["BodyMuted"])
    return Paragraph(_escape(str(value)), styles["Body"])


def _placeholder(text: str, theme: DocTheme) -> Flowable:
    return Paragraph(_escape(text), theme.styles()["Placeholder"])


# =============================================================================
# Content helpers
# =============================================================================


def _coerce_chart_list(raw: Any) -> list[ChartSpec]:
    """Normalize whatever the caller passed into a list of ChartSpec."""
    if raw is None:
        return []
    if isinstance(raw, ChartSpec):
        return [raw]
    if isinstance(raw, dict):
        # Either a single chart described as a dict, or {label: spec}
        if "source" in raw or "title" in raw:
            return [_spec_from_dict(raw)]
        return [_spec_from_dict({"title": k, "source": v}) for k, v in raw.items()]
    if isinstance(raw, list):
        return [
            spec if isinstance(spec, ChartSpec) else _spec_from_dict(spec)
            for spec in raw
        ]
    return []


def _spec_from_dict(d: Any) -> ChartSpec:
    if not isinstance(d, dict):
        return ChartSpec(title="Untitled chart", source=d)
    return ChartSpec(
        title=str(d.get("title") or d.get("name") or "Chart"),
        source=d.get("source") if "source" in d else d.get("path") if "path" in d else d.get("data"),
        caption=d.get("caption"),
        label=d.get("label"),
    )


def _split_essay_blocks(text: str) -> list[str]:
    """Split essay text into renderable paragraph blocks.

    The essay generator emits prose with double newlines between
    paragraphs and occasional Markdown-ish bold/headings. We preserve
    the paragraph breaks (one Paragraph per block) so the renderer can
    page-break between them, and let _classify_block decide which style
    to apply.
    """
    raw_blocks = [b.strip() for b in text.replace("\r\n", "\n").split("\n\n")]
    return [b for b in raw_blocks if b]


def _classify_block(block: str) -> tuple[str, str]:
    """Decide which paragraph style to use for an essay block."""
    stripped = block.strip()
    # Markdown-style heading
    if stripped.startswith("### "):
        return "H3", stripped[4:].strip()
    if stripped.startswith("## "):
        return "H2", stripped[3:].strip()
    if stripped.startswith("# "):
        return "H1", stripped[2:].strip()
    # Bold-prefixed paragraph (common in our deterministic fallback essay)
    if stripped.startswith("**") and "**" in stripped[2:]:
        return "Body", stripped
    return "Body", stripped


def _classify_block_unused():
    """(kept for reference)"""


def _section_title(name: str) -> str:
    return name.replace("_", " ").title()


def _scope_label(ctx: dict) -> str:
    """Subtitle line: ticker or portfolio scope."""
    ticker = ctx.get("ticker")
    scope = ctx.get("scope")
    if ticker:
        return str(ticker)
    if scope:
        return f"Scope: {scope}"
    return "Portfolio Memo"


# =============================================================================
# Formatting helpers
# =============================================================================


def _first(d: Any, keys: tuple) -> Any:
    """Return d[key] for the first key in ``keys`` that has a value."""
    if not isinstance(d, dict):
        return None
    for k in keys:
        v = d.get(k)
        if v is not None and v != "":
            return v
    return None


def _as_float(x: Any) -> Optional[float]:
    try:
        if x is None or isinstance(x, bool):
            return None
        return float(x)
    except (TypeError, ValueError):
        return None


def _pct(x: Any) -> Optional[str]:
    """Format a fraction or percent as 'X.X%' — heuristic on magnitude."""
    f = _as_float(x)
    if f is None:
        return None
    # If the value is plausibly already in percent units (|v| > 1.5)
    # we leave it alone; otherwise treat as fraction
    if abs(f) > 1.5:
        return f"{f:.2f}%"
    return f"{f * 100:.2f}%"


def _money(x: Any) -> Optional[str]:
    f = _as_float(x)
    if f is None:
        return None
    sign = "-" if f < 0 else ""
    f = abs(f)
    if f >= 1e12:
        return f"{sign}${f / 1e12:.2f}T"
    if f >= 1e9:
        return f"{sign}${f / 1e9:.2f}B"
    if f >= 1e6:
        return f"{sign}${f / 1e6:.2f}M"
    if f >= 1e3:
        return f"{sign}${f / 1e3:.2f}K"
    return f"{sign}${f:,.2f}"


def _fmt_metric(value: Any) -> str:
    """Generic metric formatter used by tables."""
    if value is None:
        return "—"
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, str):
        return value
    f = _as_float(value)
    if f is None:
        return str(value)
    # Heuristic: percentages and ratios get .2f; bigger numbers get money fmt
    if abs(f) >= 1e6:
        return _money(f) or str(f)
    if abs(f) < 10:
        return f"{f:.2f}"
    return f"{f:,.2f}"


def _truncate(s: str, n: int) -> str:
    if len(s) <= n:
        return s
    return s[: n - 1].rstrip() + "…"


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# =============================================================================
# Escaping
# =============================================================================


def _escape(s: Any) -> str:
    """Escape characters ReportLab Paragraph treats as XML markup."""
    return (
        str(s)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _escape_with_markup(text: str) -> str:
    """Escape but preserve a small set of Markdown-ish constructs.

    Currently: **bold** → <b>bold</b>. Anything else is plain-escaped.
    We do the bold transform BEFORE escaping the result.
    """
    parts: list[str] = []
    rest = text
    while True:
        i = rest.find("**")
        if i < 0:
            parts.append(_escape(rest))
            break
        parts.append(_escape(rest[:i]))
        j = rest.find("**", i + 2)
        if j < 0:
            # Unbalanced — fall back to literal text from here
            parts.append(_escape(rest[i:]))
            break
        parts.append(f"<b>{_escape(rest[i + 2:j])}</b>")
        rest = rest[j + 2:]
    return "".join(parts)
