import sqlite3, json
c = sqlite3.connect("data/portfolio.db")
row = c.execute("SELECT payload_json FROM agent_opinions WHERE ticker='NVDA' ORDER BY id DESC LIMIT 1").fetchone()
d = json.loads(row[0])
print("=== essay type/shape ===")
e = d.get("essay")
print("essay type:", type(e).__name__)
print("essay sample:", (str(e)[:300]))
print()
print("=== risk_flags full ===")
print(json.dumps(d.get("risk_flags"), indent=1)[:500])
print()
print("=== key_metrics type/keys ===")
km = d.get("key_metrics")
print("key_metrics type:", type(km).__name__)
print("key_metrics sample:", (json.dumps(km)[:300]) if km else km)
print()
print("=== filings_summary ===")
print(str(d.get("filings_summary"))[:200])
